/**
 * build-suite-viewer.ts — combine every per-artifact screen into ONE navigable file.
 *
 * Instead of opening N separate .html artifacts, the pipeline maintains a single
 * `ai-orchestrator/artifacts/index.html`: a sidebar lists whichever screens exist so far,
 * and the selected one renders in a seamless iframe (each artifact HTML stays fully
 * self-contained, so their differing styles never collide). Screens accumulate as the
 * pipeline runs — 1 after stage 1, +1 when its review lands, … up to the full set.
 *
 * The per-artifact .html files remain the source of each screen (generated by html.ts /
 * viewer.ts); this just stitches the present ones together. Re-run any time — it only
 * includes files that currently exist.
 *
 * Run:  node build-suite-viewer.ts     (or `npm run viewer`)
 * Out:  ai-orchestrator/artifacts/index.html
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { REPO_ROOT } from './paths.ts';

const ART_DIR = 'ai-orchestrator/artifacts';

/** Screen registry, in pipeline order. A screen appears only when its file exists. */
const REGISTRY = [
  { id: 'analyze',          label: 'Analyze',            group: '1 · Analysis',   file: '01-analysis.html' },
  { id: 'analyze-review',   label: 'Analyze — Review',   group: '1 · Analysis',   file: '01-analysis.review.html' },
  { id: 'explore',          label: 'Explore UI',         group: '2 · Exploration', file: '02-ui-exploration.html' },
  { id: 'testcases',        label: 'Test cases',         group: '3 · Test cases', file: '03-manual-testcases.html' },
  { id: 'testcases-review', label: 'Test cases — Review', group: '3 · Test cases', file: '03-manual-testcases.review.html' },
  { id: 'failures',         label: 'Failures',           group: '5 · Run',        file: '05-failures.html' },
  { id: 'report',           label: 'Report',             group: '6 · Report',     file: '06-report.html' },
];

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Build (or rebuild) the combined viewer. Returns its repo-root-relative path. */
export function buildSuiteViewer(): string {
  const screens = REGISTRY
    .map((s) => {
      const abs = resolve(REPO_ROOT, `${ART_DIR}/${s.file}`);
      if (!existsSync(abs)) return null;
      return { id: s.id, label: s.label, group: s.group, html: readFileSync(abs, 'utf8') };
    })
    .filter(Boolean) as { id: string; label: string; group: string; html: string }[];

  const payload = JSON.stringify(screens).replace(/<\/script>/gi, '<\\/script>');
  const outRel = `${ART_DIR}/index.html`;
  writeFileSync(resolve(REPO_ROOT, outRel), PAGE(payload, screens.length), 'utf8');
  return outRel;
}

const PAGE = (payload: string, count: number) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>QA Suite — ${count} screen${count === 1 ? '' : 's'}</title>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet" />
<style>
  :root { --sidebar-w: 260px; --header-h: 52px; }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; height: 100%; }
  body { font-family: 'IBM Plex Sans', system-ui, sans-serif; background: #e9ebef; color: #33394a; -webkit-font-smoothing: antialiased; }
  .app { display: flex; height: 100vh; overflow: hidden; }

  /* ===== sidebar ===== */
  .side { width: var(--sidebar-w); flex: none; background: #fff; border-right: 1px solid #d7dae0; display: flex; flex-direction: column; overflow-y: auto; }
  .brand { display: flex; align-items: center; gap: 10px; padding: 15px 18px; border-bottom: 1px solid #eef0f3; position: sticky; top: 0; background: #fff; }
  .brand .dot { width: 9px; height: 9px; border-radius: 50%; background: oklch(0.6 0.15 150); flex: none; }
  .brand b { font: 700 14px/1.1 'IBM Plex Sans', sans-serif; color: #15171d; }
  .brand span { font: 500 11px/1 'IBM Plex Mono', monospace; color: #8a93a2; margin-left: auto; }
  .nav { padding: 10px 10px 20px; }
  .grp { font: 600 9.5px/1 'IBM Plex Mono', monospace; letter-spacing: .1em; text-transform: uppercase; color: #a7aebb; padding: 14px 10px 7px; }
  .item { display: flex; align-items: center; gap: 9px; width: 100%; text-align: left; cursor: pointer; border: 1px solid transparent; background: transparent; border-radius: 8px; padding: 9px 11px; margin-bottom: 2px; font: 500 13px/1.25 'IBM Plex Sans', sans-serif; color: #3d4453; transition: background .12s, border-color .12s; }
  .item:hover { background: #f4f6f8; }
  .item.active { background: oklch(0.965 0.03 255); border-color: oklch(0.86 0.07 255); color: oklch(0.4 0.13 255); font-weight: 600; }
  .item .tick { font: 600 11px/1 'IBM Plex Mono', monospace; color: oklch(0.5 0.13 150); }
  .item.active .tick { color: oklch(0.45 0.13 255); }

  /* ===== main ===== */
  .main { flex: 1; min-width: 0; display: flex; flex-direction: column; }
  .top { height: var(--header-h); flex: none; display: flex; align-items: center; gap: 12px; padding: 0 18px; background: color-mix(in srgb, #e9ebef 80%, transparent); backdrop-filter: blur(8px); border-bottom: 1px solid #d7dae0; }
  .menu-btn { display: none; background: #fff; border: 1px solid #d7dae0; border-radius: 8px; width: 34px; height: 34px; cursor: pointer; font-size: 18px; }
  .top .crumb { font: 600 13px/1.2 'IBM Plex Sans', sans-serif; color: #1a1c22; }
  .top .crumb s { text-decoration: none; color: #8a93a2; font-weight: 500; }
  .top .count { margin-left: auto; font: 500 11.5px/1 'IBM Plex Mono', monospace; color: #8a93a2; }
  .frame-wrap { flex: 1; min-height: 0; }
  iframe { width: 100%; height: 100%; border: none; display: block; background: #e9ebef; }
  .empty { padding: 60px; text-align: center; color: #8a93a2; font: 400 14px/1.6 'IBM Plex Sans', sans-serif; }

  .overlay { display: none; position: fixed; inset: 0; background: rgba(20,24,33,.35); z-index: 20; }
  @media (max-width: 820px) {
    .side { position: fixed; z-index: 30; height: 100vh; transform: translateX(-100%); transition: transform .22s ease; box-shadow: 0 10px 40px rgba(20,24,33,.2); }
    .side.open { transform: none; }
    .overlay.show { display: block; }
    .menu-btn { display: grid; place-items: center; }
  }
</style>
</head>
<body>
<div class="app">
  <aside class="side" id="side">
    <div class="brand"><span class="dot"></span><b>QA Suite</b><span id="scount"></span></div>
    <nav class="nav" id="nav"></nav>
  </aside>
  <div class="overlay" id="overlay"></div>
  <div class="main">
    <div class="top">
      <button class="menu-btn" id="menuBtn" aria-label="Screens">☰</button>
      <div class="crumb" id="crumb"></div>
      <div class="count" id="count"></div>
    </div>
    <div class="frame-wrap"><iframe id="frame" title="screen"></iframe></div>
  </div>
</div>

<script type="application/json" id="screens">${payload}</script>
<script>
  var SCREENS = JSON.parse(document.getElementById('screens').textContent);
  var byId = {}; SCREENS.forEach(function (s) { byId[s.id] = s; });
  var nav = document.getElementById('nav');
  var frame = document.getElementById('frame');
  var side = document.getElementById('side');
  var overlay = document.getElementById('overlay');

  document.getElementById('scount').textContent = SCREENS.length + ' screen' + (SCREENS.length === 1 ? '' : 's');
  document.getElementById('count').textContent = SCREENS.length + ' / ' + SCREENS.length;

  // group the nav
  var groups = [];
  SCREENS.forEach(function (s) { var g = groups.find(function (x) { return x.group === s.group; }); if (!g) { g = { group: s.group, items: [] }; groups.push(g); } g.items.push(s); });
  if (!SCREENS.length) { nav.innerHTML = '<div class="empty">No screens yet — run a pipeline stage.</div>'; }
  groups.forEach(function (g) {
    var h = document.createElement('div'); h.className = 'grp'; h.textContent = g.group; nav.appendChild(h);
    g.items.forEach(function (s) {
      var b = document.createElement('button'); b.className = 'item'; b.dataset.id = s.id;
      b.innerHTML = '<span class="tick">' + (s.id.indexOf('review') >= 0 ? '✓' : '◆') + '</span><span>' + s.label + '</span>';
      b.addEventListener('click', function () { select(s.id); closeDrawer(); });
      nav.appendChild(b);
    });
  });

  function select(id) {
    var s = byId[id]; if (!s) { s = SCREENS[0]; if (!s) return; id = s.id; }
    frame.srcdoc = s.html;
    document.getElementById('crumb').innerHTML = '<s>QA Suite /</s> ' + s.label;
    var items = nav.querySelectorAll('.item');
    for (var i = 0; i < items.length; i++) items[i].classList.toggle('active', items[i].dataset.id === id);
    if (history.replaceState) history.replaceState(null, '', '#' + id);
  }
  function openDrawer() { side.classList.add('open'); overlay.classList.add('show'); }
  function closeDrawer() { side.classList.remove('open'); overlay.classList.remove('show'); }
  document.getElementById('menuBtn').addEventListener('click', function () { side.classList.contains('open') ? closeDrawer() : openDrawer(); });
  overlay.addEventListener('click', closeDrawer);

  var start = (location.hash || '').slice(1);
  select(byId[start] ? start : (SCREENS[0] && SCREENS[0].id));
</script>
</body>
</html>
`;

// Run directly: `tsx build-suite-viewer.ts`
if (import.meta.url === `file://${process.argv[1]}`) {
  const out = buildSuiteViewer();
  console.log('✓ combined viewer → ' + out);
}
